[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['cd web && npm ci']

[phases.build]
cmds = ['cd web && npm run build']

[start]
cmd = 'cd web && npm run start'

[variables]
NODE_ENV = 'production'
PORT = '4000'